### ISSUE TITLE
[ユーザー貢献度機能_01]ユーザー貢献度のテーブルを作成する

### ISSUE THREAD

**Issue by sion001** [sion001/diver_23#6]
- [x] カラムは下記の通りにする

- [ 質問 or 回答 ] (choice_id)ID : integer
- 質問回答判別フラグ(choice_type) : integer　0:質問, 1:回答　default 0
- ユーザーID(user_id) : integer
- ポイント(point) : integer default 0

※必要なカラムは適時追加し、他メンバーに連携すること

**Comment by suzukisan22** [comment]
カラム名の編集
