### ISSUE TITLE
[その他]本番環境でのFacebook、Googleログインを可能にする

### ISSUE THREAD

**Issue by kakiuchis** [sion001/diver_23#72]
- [x] Facebookの本番環境の登録を行う（https://developers.facebook.com/）

- [x] Googleの本番環境の登録を行う（https://console.developers.google.com/）

- [x] herokuにFACEBOOK_ID_PRODUCTION, FACEBOOK_SECRET_PRODUCTION, GOOGLE_ID_PRODUCTION, GOOGLE_SECRET_PRODUCTIONの登録を行う

**Comment by sion001** [comment]
Facebookは本番環境でログインできるようになった。
Googleは現在調整中。
herokuに環境変数設定済

**Comment by sion001** [comment]
Google認証調整完了。
